/**
 *                  _     _  __  __ ___  __  __
 *                 (_)   | ||  \/  |__ \|  \/  |
 *  _ __ __ _ _ __  _  __| || \  / |  ) | \  / |
 * | '__/ _` | '_ \| |/ _` || |\/| | / /| |\/| |
 * | | | (_| | |_) | | (_| || |  | |/ /_| |  | |
 * |_|  \__,_| .__/|_|\__,_||_|  |_|____|_|  |_|
 *           | |
 *           |_|
 * 
 * Simple rapidM2M "Hello World"
 * Prints "Hello World" to the development console once after starting the script.
 * 
 * Compatible with every rapidM2M hardware.
 *
 * @version 20190816
 */

/* Application entry point */
main()
{
  #log("Hello World");
}